### ISSUE TITLE
Example ops file for use with cf-deployment

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry-incubator/bits-service#8]
CAPI team has just started playing around with the bits service. We threw together this ops file to add a single bits service VM with webdav to cf-deployment. Needs some work to make it more generalized but figured we share it:

```yaml
---
# Summary
# --------
# TODO
#
# Optional properties:
#
# - TODO

- type: replace
  path: /instance_groups/-
  value:
    name: bits-service
    instances: 1
    azs: [z1]
    vm_type: m3.medium
    persistent_disk: 6064
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: bits-service
        release: bits-service
        properties:
          bits-service:
            private_endpoint: http://bits-service.service.cf.internal
            public_endpoint: http://bits-service.((system_domain))
            secret: "((bits_services_secret))"
            signing_users:
              - username: admin
                password: "((bits_service_signing_password))"
            app_stash:
              blobstore_type: webdav
              directory_key: app_stash
              resource_directory_key: app_stash
              webdav_config: &webdav-config
                ca_cert: "((blobstore_tls.ca))"
                password: "((blobstore_admin_users_password))"
                private_endpoint: https://blobstore.service.cf.internal:4443
                public_endpoint: https://blobstore.((system_domain))
                username: blobstore-user
            buildpacks:
              blobstore_type: webdav
              buildpack_directory_key: buildpacks
              directory_key: buildpacks
              webdav_config: *webdav-config
            droplets:
              blobstore_type: webdav
              directory_key: droplets
              droplet_directory_key: droplets
              webdav_config: *webdav-config
            packages:
              app_package_directory_key: packages
              blobstore_type: webdav
              directory_key: packages
              webdav_config: *webdav-config
            cc_updates:
              ca_cert: "((cc_tls.ca))"
              client_cert: "((cc_tls.certificate))"
              client_key: "((cc_tls.private_key))"
      - name: consul_agent
        release: consul
        consumes:
          consul_common: {from: consul_common_link}
          consul_server: nil
          consul_client: {from: consul_client_link}
        properties:
          consul:
            agent:
              services:
                bits-service: {}
      - name: route_registrar
        release: routing
        properties:
          route_registrar:
            routes:
              - name: bits-service
                port: 80
                registration_interval: 20s
                uris:
                  - bits-service.((system_domain))
                tags:
                  component: bits-service

- type: replace
  path: /variables/-
  value:
    name: bits_service_secret
    type: password

- type: replace
  path: /variables/-
  value:
    name: bits_service_signing_password
    type: password

- type: replace
  path: /releases/-
  value:
    name: bits-service
    version: latest
    # TODO: get a URL
```
